language: c++
dist: bionic
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y scons
  - sudo apt-get install -y libboost-all-dev

defore_script:
  - git clone https://github.com/xanthospap/ggdatetime.git && cd ggdatetime
  - sudo scons install
  - cd ../
  - git clone https://github.com/xanthospap/matvec.git && cd matvec
  - sudo scons install
  - cd ../
  - sudo ldconfig

script:
  - scons
  - scons debug=1
